version: '3.9'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.perseo-react.dev
    command: bash -c "npm install & npm run start-dev"
    volumes:
      - './perseo-react/:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - web
    stdin_open: true
    tty: true
  web:
    build:
      context: .
      dockerfile: Dockerfile.perseo-backend.dev
    entrypoint: "./docker/perseo-backend/scripts/entrypoint.sh"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    ports:
      - '8080:8080'
    volumes: 
      - ./perseo/:/usr/src/app
    depends_on:
      - mysql
    networks:
      - networkweb
    environment:
      RACK_TIMEOUT_SERVICE_TIMEOUT: 60000
    stdin_open: true
    tty: true
  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=32505856 # Set max_allowed_packet to 256M (or any other value)
    environment:
      MYSQL_ROOT_PASSWORD: Mysql2021!
      MYSQL_DATABASE: perseo
    ports:
      - '3306:3306'
    volumes:
      - ./docker/perseo-backend/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - database_data:/var/lib/mysql
    networks:
      - networkweb
  adminer:
    image: adminer
    ports:
      - 8082:8080
    depends_on:
      - mysql
    networks:
      - networkweb

networks:
  networkweb:
    driver: bridge
volumes:
  database_data:
